:PROPERTIES:
:ID:       986b05f1-5758-4213-aff1-66f889f912b2
:ROAM_REFS: cite:cunningham_principal_2022
:END:
#+title: Principal Manifold Flows
#+startup: latexpreview
#+filetags: :DimensionReduction:MachineLearning:

[[id:17383d23-7ad0-4b99-a99f-660cd2984878][Normalizing flows]] are based on a succession of diffeomorphism, which
transport an arbitrary distribution into a simpler one
(normal). However, the imposed bijectivity can be an issue for trainings
* Preliminaries
** Normalizing flows
Let $f: \mathcal{Z}\subseteq \mathbb{R}^N \rightarrow
\mathcal{X}\subseteq \mathbb{R}^N$ be a parametric bijective function
from a latent variable to a data point $x = f(z)$. Its inverse if
$g$. The Jacobian of $f$ is $J$, and the jacobian of $g$ is $G$.
\begin{equation}
\log p_X(x) = \log p_Z(z) + \log \lvert G \rvert
\end{equation}
** Injective case
if $f$ maps a low-dimensional $z$ to a higher-dimensional $x$, the
change of variable formula becomes
\begin{equation}
\log p_X(x) = \log p_Z(z)- \frac{1}{2}\log \lvert J^T J\rvert\quad x = f(z)
\end{equation}
which is valid on the manifold $f(\mathcal{Z})$
** Principal components of a flow
  Let $x$ be a data point, $f$ invertible function of a flow, and $\sigma > 0$ is a scalar.
  For samples generated by
  \begin{equation}
 x' = f(f^{-1}(x) + \sigma \epsilon) \quad \epsilon \sim \mathcal{N}(0, I)
 \end{equation}
 we have
 \begin{equation}
 \frac{1}{\sigma}(x' - x) \rightarrow_{\mathrm{D}} \mathcal{N}(0, J J^T) \quad \sigma \rightarrow 0
 \end{equation}
 So we can use the eigenvectors of $J J^T$ to define the principal components of a flow.
*** Principal components of a flow at $x$
    The PCF at $x$ are the eigenvectors of $JJ^T$, where $J$ is the
    jacobian matrix of $f$ at $x$. Ordered according to descending
    vectors.
*** Principal manifold of a flow
    The PM of a flow the path formed by integrating along the PC
    starting at $x_0$. Let $\mathbb{K}$ be a subset of $\{1,\dots
    \dim(z)\}$. A PM of dimension $|\mathbb{K}|$ is the solution of
    \begin{equation}
 \frac{\mathrm{d} x(t)}{\mathrm{d}t} = w_{\mathbb{K}}(x(t)),\quad x(0) = x_0
 \end{equation}
 where $w_{\mathbb{K}}(x(t)) = \hat{w}_{\mathbb{K}}
 \sqrt{\Lambda_{\mathbb{K}}}$ are the PC with indices in $\mathbb{K}$
 at $x(t)$ scaled by the sqrt of the corresponding eigenvalues.

** Contours of NF
*** Def
    Let $\mathbb{K}$ be a subset of $\{1,\cdots,\dim(z)\}$ and let
    $z_{\mathbb{K}}$ be the latent variables with indices in
    $\mathbb{K}$.  The contour obtained by varying $z_{\mathbb{K}}$ and
    fixing all other variables is denoted as
    $f_{\mathbb{K}}(z_{\mathbb{K}})$
*** Properties
    We assume $\mathcal{P}$, a partition over the indices in the latent
    space, and we assume that
    \begin{equation}
 p_Z(z) = \prod_{\mathbb{K}\in \mathcal{P}} p_{\mathbb{K}}(z_{\mathbb{K}})
 \end{equation}
 The jacobian matrix of $f_{\mathbb{K}}(z_{\mathbb{K}})$ is denoted by
 $J_{\mathbb{K}}$ and is the matrix containing the columns of $J$ with
 indices in $\mathbb{K}$. The log-lik of a contour is $\mathcal{L}_{\mathbb{K}}$
 \begin{equation}
 \mathcal{L}_{\mathbb{K}} = \log p(f_\mathbb{K}(z_{\mathbb{K}}) = \log p_{\mathbb{K}}(z_{\mathbb{K}}) - \frac{1}{2} \log \lvert J_{\mathbb{K}}^T J_{\mathbb{K}}\rvert
 \end{equation}
** (Pointwise) Mutual information between contours
*** Def

    Let $S$, $T$ subsets of a latent variable: $z_S$, $z_T$, and their union $z_{S + T}$
    \begin{equation}
 \mathcal{I}_{S, T} = \log \frac{p(f_{S+T}(z_{S+T}))}{p(f_S(z_S) p(f_T(z_T))} = \mathcal{L}_{S+T} - \mathcal{L}_{S} - \mathcal{L}_T
 \end{equation}

 $\mathcal{I}_{S,T}$ is non-negative, and zero when the contours
 intersect orthogonally. More generally, we can define the mutual
 information using a partition.
*** Pointwise mutual information of a partition

    \begin{equation}
 \mathcal{I}_{\mathcal{P}} = \log p_X(f(z)) - \sum_{\mathbb{K} \in \mathcal{P}} \mathcal{L}_{\mathbb{K}}
 \end{equation}
* Principal Manifold Flows
** PF
*** Def
    A Principal manifold flow (PF) is a normalizing flow that satisfies $\mathcal{I}_\mathcla{P}=0$
*** Theorem: contours of PFs
    The contours of a Principal manifold flow are principal manifolds
   
